spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/chatter
    username: chatter
    password: chatter
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    show-sq: true
server:
  port: 8081

  